title: Software Book
description: A Documentation medium for my Software Engineering learnings.
theme: just-the-docs
timezone: Asia/Kolkata
color_scheme: light

url: https://sbook.subramanyam.dev
favicon:

gh_edit_repository: "https://github.com/Subramanyam-r/sbook"
gh_edit_branch: "main"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit Source"
gh_edit_view_mode: "tree"

last_edit_timestamp: true
last_edit_time_format: "%B %d, %Y"

nav_enabled: true

aux_links_new_tab: true
aux_links:
    "About": "https://subramanyam.dev"
    "Home": "/"
    "Blog": "/blog"

back_to_top: true
back_to_top_text: "Back to top"

plugins:
    - jekyll-last-modified-at

last-modified-at:
    date-format: "%d-%b-%y"

callouts:
    highlight:
        color: yellow
    important:
        title: Important
        color: blue
    new:
        title: New
        color: green
    note:
        color: purple
    warning:
        title: Warning
        color: red

defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          nav_exclude: true

permalink: /blog/:title/
