title: DSA Docs
description: Documentation site for my DSA Learnings
theme: just-the-docs
timezone: Asia/Kolkata

url: https://dsa.subramanyam.dev
favicon: 

gh_edit_repository: "https://github.com/Subramanyam-r/dsa-docs"
gh_edit_branch: "main"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_view_mode: "tree"

last_edit_timestamp: true
last_edit_time_format: "%B %d, %Y"

nav_enabled: true

aux_links_new_tab: true
aux_links:
  "About": "https://subramanyam.dev"

back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll-last-modified-at

last-modified-at:
  date-format: '%d-%b-%y'
